import fs from 'node:fs/promises';
import path from 'node:path';
import { h } from 'preact';
import render from 'preact-render-to-string';

// Load CSS modules mapping generated by rollup
export async function loadCSSModulesMapping() {
  try {
    const mappingPath = path.join(__dirname, './ui/css-modules-mapping.json');
    const mappingData = await fs.readFile(mappingPath, 'utf8');
    const mapping = JSON.parse(mappingData);
    console.log('CSS modules mapping loaded:', mapping);
    return mapping;
  } catch (err) {
    console.error('Error loading CSS modules mapping:', err);
    return {};
  }
}

// Helper function to get sketch directories with timestamps
export async function getSketchDirs(sketchesPath: string) {
  const files = await fs.readdir(sketchesPath, { withFileTypes: true });
  const dirsWithTimestamps = await Promise.all(
    files
      .filter((file) => file.isDirectory())
      .map(async (dir) => {
        const dirPath = path.join(sketchesPath, dir.name);
        const files = await fs.readdir(dirPath);
        const tsFiles = files.filter((file) => file.endsWith('.ts'));
        const tsStats = await Promise.all(tsFiles.map((file) => fs.stat(path.join(dirPath, file))));
        const lastModified = Math.max(...tsStats.map((stat) => stat.mtime.getTime()));

        return {
          name: dir.name,
          lastModified,
        };
      })
  );

  return dirsWithTimestamps.sort((a, b) => a.name.localeCompare(b.name));
}

// Helper function to render the main page
export async function renderMainPage(
  sketchesPath: string,
  htmlTemplatePath: string,
  SketchListComponent: any,
  styles: any,
  sketchName?: string
) {
  const sortedDirs = await getSketchDirs(sketchesPath);

  // Create SketchList with processed styles
  const sketchListHtml = render(h(SketchListComponent, { dirs: sortedDirs }));

  const data = await fs.readFile(htmlTemplatePath, 'utf8');
  const renderedHtml = data
    .replace('${sketchListPlaceholder}', sketchListHtml)
    .replace('${initialData}', JSON.stringify({ dirs: sortedDirs, initialSketch: sketchName || null }));

  return renderedHtml;
}
