import fs from 'node:fs/promises';
import path from 'node:path';
import { h } from 'preact';
import render from 'preact-render-to-string';

const sketchesPath = path.join(__dirname, '../../sketches');

// Path utilities
export const paths = {
  public: () => path.join(__dirname, '../public'),
  uiIndex: () => path.join(__dirname, './ui/index.html'),
  sketches: () => sketchesPath,
  sketch: (sketchName: string) => path.join(sketchesPath, sketchName),
  dist: (sketchName: string) => path.join(sketchesPath, sketchName, 'dist'),
  src: (sketchName: string) => path.join(sketchesPath, sketchName, 'src'),
  html: (sketchName: string) => path.join(sketchesPath, sketchName, 'dist', `${sketchName}.html`),
  params: (sketchName: string) => path.join(sketchesPath, sketchName, 'src', `${sketchName}.params.ts`),
  template: (sketchName: string) => path.join(sketchesPath, sketchName, 'src', `${sketchName}.params.tpl`),
  serverHandler: (sketchName: string) => path.join(sketchesPath, sketchName, 'src', `${sketchName}.server.js`),
};

// Load CSS modules mapping generated by rollup
export async function loadCSSModulesMapping() {
  try {
    const mappingPath = path.join(__dirname, './ui/css-modules-mapping.json');
    const mappingData = await fs.readFile(mappingPath, 'utf8');
    const mapping = JSON.parse(mappingData);
    console.log('CSS modules mapping loaded');

    return mapping;
  } catch (err) {
    console.error('Error loading CSS modules mapping:', err);

    return {};
  }
}

export async function getSketchDirsData(sketchesPath: string) {
  const files = await fs.readdir(sketchesPath, { withFileTypes: true });

  const dirsWithTimestamps = await Promise.all(
    files
      .filter((file) => file.isDirectory())
      .map(async (dir) => {
        const dirPath = path.join(sketchesPath, dir.name);

        // Get all TypeScript files recursively
        const getAllTsFiles = async (dirPath: string): Promise<string[]> => {
          const items = await fs.readdir(dirPath, { withFileTypes: true });
          const files: string[] = [];

          for (const item of items) {
            const itemPath = path.join(dirPath, item.name);

            if (item.isDirectory() && !item.name.startsWith('.') && item.name !== 'node_modules') {
              files.push(...(await getAllTsFiles(itemPath)));
            } else if (item.isFile() && (item.name.endsWith('.ts') || item.name.endsWith('.tsx'))) {
              files.push(itemPath);
            }
          }

          return files;
        };

        const tsFiles = await getAllTsFiles(dirPath);

        if (tsFiles.length === 0) {
          return {
            name: dir.name,
            lastModified: 0,
          };
        }

        const tsStats = await Promise.all(tsFiles.map((file) => fs.stat(file)));
        const lastModified = Math.max(...tsStats.map((stat) => stat.mtime.getTime()));

        return {
          name: dir.name,
          lastModified,
        };
      })
  );

  console.log(dirsWithTimestamps);

  return dirsWithTimestamps.sort((a, b) => a.name.localeCompare(b.name));
}

export async function renderMainPage(
  sketchesPath: string,
  htmlTemplatePath: string,
  SketchListComponent: any,
  sketchName?: string
) {
  const sortedDirs = await getSketchDirsData(sketchesPath);

  const sketchListHtml = render(h(SketchListComponent, { dirs: sortedDirs }));

  const data = await fs.readFile(htmlTemplatePath, 'utf8');
  const renderedHtml = data.replace('${sketchListPlaceholder}', sketchListHtml).replace(
    '${initialData}',
    JSON.stringify({
      dirs: sortedDirs,
      initialSketch: sketchName || null,
    })
  );

  return renderedHtml;
}
